### PR TITLE
Return 400 response when request doesn't originate from https

### PR DESCRIPTION
**Pull request by dividehex**
Let's explicitly not redirect non https and just return a 400

### CODE REVIEW

**Comment by djmitche** [comment]
Is this problematic for local development?

**Comment by dividehex** [comment]
It could be problematic.  I tested this locally by using the firefox addon Poster, which allows you to craft custom http/https requests. This could be also be done with curl. Even if we did a redirect, local development would still need some hacking to enable https under gunicorn or flask to simulate the heroku environment. Another option would be a env var to bypass it for debugging locally.

https://addons.mozilla.org/en-US/firefox/addon/poster/

**Comment by djmitche** [comment]
For other TC services, there are "forceSsl" and "trustProxy" config options which configure the service to require SSL and to trust the Heroku proxy.

**Comment by djmitche** [comment]
https://github.com/taskcluster/taskcluster-secrets/blob/master/config/defaults.js#L35 for example

**Comment by dividehex** [comment]
You are correct, this can be done better with flask-sslify and proxyfix.

**Pull request closed without merging**
